version: "3.8"

services:
  mongo:
    image: mongo:6
    container_name: service_practice_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  redis:
    image: redis:7
    container_name: service_practice_redis
    restart: always
    ports:
      - "6379:6379"
  rabbitmq:
    image: rabbitmq:3-management
    container_name: service_practice_rabbitmq
    ports:
      - "5672:5672" # para conexion AMQP
      - "15672:15672" # para acceder a panel web
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

volumes:
  mongo_data: